syntax on
set incsearch
set expandtab
set termencoding=utf-8
set smarttab
set ts=4
set shiftwidth=4
set number
set t_Co=256
set notimeout
set nocompatible
set ttimeout
set ttimeoutlen=10
set ttyfast

" Enable Pathogen package manager
runtime autoload/pathogen.vim
call pathogen#infect()
call pathogen#helptags()
filetype plugin on
filetype plugin indent on

" Set color theme
set background=dark
colorscheme solarized

" Tabs
map <silent> <C-T> :tabnew<CR>
map <silent> <C-J> :tabprevious<CR>
map <silent> <C-K> :tabnext<CR>
imap <silent> <C-T> <ESC>:tabnew<CR>i
imap <silent> <C-W> <ESC>:tabclose<CR>i

nnoremap <silent> <F7> :TagbarToggle<CR> 
nnoremap <silent> <F8> :TlistToggle<CR> 
nnoremap <silent> <F3> :NERDTreeToggle<CR> 

" Syntastic
let g:syntastic_enable_signs = 1
let g:syntastic_error_symbol         = '✗'
let g:syntastic_style_error_symbol   = '✗'
let g:syntastic_warning_symbol       = '⚠'
let g:syntastic_style_warning_symbol = '⚠'


" Powerline
set laststatus=2 " Always display the statusline in all windows
set noshowmode " Hide the default mode text (e.g. -- INSERT -- below the statusline)
python import sys; sys.path.append("/usr/local/lib/python2.7/site-packages/")
python from powerline.vim import setup as powerline_setup
python powerline_setup()
python del powerline_setup