# Based on the output of `brew bundle dump` (which must be run outside of tmux).
#
# {{ ansible_managed }}

cask_args appdir: '/Applications'

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "git"
brew "neovim"
brew "python"
brew "rbenv"
brew "tmux"

# General applications.
cask "1password"
cask "google-chrome"
cask "iterm2"
cask "skype"
cask "spotify"
cask "sublime-text"
cask "vlc"
