# a mouse
set -g mode-mouse on

# command prefix 
set -g prefix C-a  

# start window indexing at one instead of zero
set -g base-index 1

unbind % # remove default binding since replacing
bind \ split-window -h
bind - split-window -v

# powerline setup
source /usr/local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf

